// © 2022 Unit Circle Inc.
//
// AUTOGENERATED BY utf8valid.py version:
//   927ef0f1175f858c212bb43fa30567894b0bcf1cd050ac8cc6d590bc9f754581
//
// Implementation inspired from:
//   http://bjoern.hoehrmann.de/utf-8/decoder/dfa/
// Details taken from:
//   https://tools.ietf.org/html/rfc3629 section 4 BNF

#pragma once

#define UTF8_ACCEPT 0
#define UTF8_ERROR 88

static const uint8_t utf8cc[] = {
 7, 7, 7, 7, 7, 7, 7, 7,  7, 7, 7, 7, 7, 7, 7, 7,
 8, 8, 8, 8, 8, 8, 8, 8,  8, 8, 8, 8, 8, 8, 8, 8,
 9, 9, 9, 9, 9, 9, 9, 9,  9, 9, 9, 9, 9, 9, 9, 9,
 9, 9, 9, 9, 9, 9, 9, 9,  9, 9, 9, 9, 9, 9, 9, 9,
10,10, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0,
 1, 2, 2, 2, 2, 2, 2, 2,  2, 2, 2, 2, 2, 3, 2, 2,
 4, 5, 5, 5, 6,10,10,10, 10,10,10,10,10,10,10,10,
};

static const uint8_t utf8stt[] = {
11,33,22,44,55,66,77,88,88,88,88, 88,88,88,88,88,88,88, 0, 0, 0,88,
88,88,88,88,88,88,88,11,11,11,88, 88,88,88,88,88,88,88,88,88,11,88,
88,88,88,88,88,88,88,11,11,88,88, 88,88,88,88,88,88,88,88,22,22,88,
88,88,88,88,88,88,88,22,22,22,88, 88,88,88,88,88,88,88,22,88,88,88,
};

static bool is_valid_utf8(const char *str, size_t len) {
  uint32_t type;
  uint32_t state = UTF8_ACCEPT;

  while (len-- > 0) {
    uint8_t c = (uint8_t) *str++;
    if (c < 0x80) {
      if (state != UTF8_ACCEPT) return false;
    }
    else {
      type = utf8cc[c-0x80];
      state = utf8stt[state + type];
      if (state == UTF8_ERROR) break;
    }
  }
  return state == UTF8_ACCEPT;
}
