CFLAGS += -DTX_PIN_NUMBER=6 -DRX_PIN_NUMBER=8
CFLAGS += -DLED_PIN_NUMBER=13 -DWAKEUP_PIN_NUMBER=11
ASMFLAGS += -DTX_PIN_NUMBER=6 -DRX_PIN_NUMBER=8
ASMFLAGS += -DLED_PIN_NUMBER=13  -DWAKEUP_PIN_NUMBER=11

#SDK_ROOT := nordic/nRF5_SDK_17.1.0_ddde560
SDK_ROOT := src-nordic

include config/nrf52840.mk
